---
title: "Love Lab Package Download Stats"
format:
  html:
    self-contained: true
execute:
  echo: false
  message: false
  warning: false
  fig-align: center
---

[Average Bioc package downloads](https://bioconductor.org/packages/stats/index.html) 
from unique IPs, averaged over months of Jan-Apr:

```{r}
#| label: setup
library(BiocPkgTools)
library(dplyr)
library(lubridate)
library(ggplot2)
```

```{r}
#| label: load-data
#| cache: true
pkgs <- c(
  "DESeq2","apeglm",
  "tximport","tximeta",
  "plyranges","nullranges",
  "plyxp"
)
bioc <- biocDownloadStats() |>
  filter(pkgType == "software") |>
  filter(Package %in% pkgs) |>
  filter(!is.na(Date))
```

```{r}
#| label: compute-stats
# focus on Jan-Apr
stats <- bioc |>
  filter(Month %in% c("Jan", "Feb", "Mar", "Apr")) |>
  group_by(Package, Year) |>
  summarise(
    Avg_DLs = mean(Nb_of_distinct_IPs, na.rm = TRUE),
    .groups = "drop"
  ) |>
  arrange(Year)
```

```{r}
#| label: plot
#| fig-alt: "Line plot of average Jan-Apr distinct IPs by year"
pkg_order <- stats |>
  filter(Year == max(Year)) |>
  arrange(desc(Avg_DLs)) |>
  pull(Package)

stats |>
  filter(Year >= 2016) |>
  filter(Avg_DLs > 10) |>
  mutate(Package = factor(Package, levels = pkg_order)) |>
  ggplot(aes(
    Year, Avg_DLs, 
    linetype = Package, color = Package, group = Package)
  ) +
  geom_line(linewidth=1) +
  scale_y_log10() +
  theme(legend.position = "bottom") +
  guides(
    color = guide_legend(keywidth = 3),
    linetype = guide_legend(keywidth = 3)
  )
```

```{r}
#| label: table
stats |>
  filter(Year %in% c(2025, 2026)) |>
  select(Package, Year, Avg_DLs) |>
  tidyr::pivot_wider(names_from = Year, values_from = Avg_DLs) |>
  mutate(pct_change = round((`2026` - `2025`) / `2025` * 100, 1)) |>
  arrange(desc(`2026`)) |>
  knitr::kable(
    col.names = c("Package", "2025", "2026", "% Change"),
    digits = 0
  )
```
